#!/bin/sh
#chkconfig: 35 81 80
#description: nginx
 
nginx_base_dir="/usr/local/nginx"
nginx_daemon="${nginx_base_dir}/sbin/nginx"
nginx_conf="${nginx_base_dir}/conf/nginx.conf"

logdir="/usr/local/nginx/logs/"
cronolog="/usr/local/cronolog/sbin/cronolog"
	
launch_signal() {
	${nginx_daemon} -s ${1} &>/dev/null
}

checkconfig() {
	${nginx_daemon} -c ${nginx_conf} -t &>/dev/null
}

check() {
	${nginx_daemon} -t -c ${nginx_conf}
}
	
start() {
	[ -r ${nginx_conf} ] || exit 1 
	cronolog_start || return 7
	checkconfig && ${nginx_daemon} -c ${nginx_conf} &>/dev/null || return ${?}
	echo "nginx start"
}

cronolog_start() {
    if ! [ -p $logdir/access_pipe ]; then
       rm -f $logdir/access_pipe
       rm -f $logdir/error_pipe
       mkfifo $logdir/access_pipe
       mkfifo $logdir/error_pipe
    fi

    /bin/sh -c "/bin/cat $logdir/access_pipe | $cronolog $logdir/%Y%m/access.zchat.kr_%Y%m%d &"
    /bin/sh -c "/bin/cat $logdir/error_pipe  | $cronolog $logdir/error.zchat.kr_%Y%m%d &"
}
	
stop() {
	launch_signal stop
	echo "nginx stop"
}
	
reload() {
	checkconfig && launch_signal reload || return ${?}
}
 
restart() {
	stop && start
}
 
show_usage() {
	echo "Usage: ${0} {start|stop|restart|reload|check}"
	exit 3
}
 
case "${1}" in
	start|stop|restart|reload|check)
		[ -x ${nginx_daemon} ] || exit 2
		${1}
		;;
	*)
		show_usage
		;;
esac
